[package]
name = "web-static-pack"
version = "0.1.0"
authors = ["Paweł Kubrak <peku33@gmail.com>"]
edition = "2018"

description = "Embed static resources (GUI, assets, images, styles, html) in executable. Serve them from web application with ease."

[dependencies]
